// Date: 11/26/2014 2:41:22 PM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX


package com.devcon3.botbuddy.mob;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelBiped;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.client.renderer.entity.RenderBiped;
import net.minecraft.entity.Entity;
import net.minecraft.util.MathHelper;

import java.util.Map;

public class BotBuddy extends ModelBase
{
    //fields
    ModelRenderer rightearlower;
    ModelRenderer leftearlower;
    ModelRenderer rightearupper;
    ModelRenderer leftearupper;
    ModelRenderer cordmid;
    ModelRenderer cordupper;
    ModelRenderer cordlower;
    ModelRenderer head;
    ModelRenderer body;
    ModelRenderer rightarm;
    ModelRenderer leftarm;
    ModelRenderer rightleg;
    ModelRenderer leftleg;

    public BotBuddy()
    {
        textureWidth = 64;
        textureHeight = 32;

        rightearlower = new ModelRenderer(this, 0, 0);
        rightearlower.addBox(0F, 0F, 0F, 3, 1, 1);
        rightearlower.setRotationPoint(-7F, -4F, 0F);
        rightearlower.setTextureSize(64, 32);
        rightearlower.mirror = true;
        setRotation(rightearlower, 0F, 0F, 0F);
        leftearlower = new ModelRenderer(this, 0, 0);
        leftearlower.addBox(0F, 0F, 0F, 3, 1, 1);
        leftearlower.setRotationPoint(4F, -4F, 0F);
        leftearlower.setTextureSize(64, 32);
        leftearlower.mirror = true;
        setRotation(leftearlower, 0F, 0F, 0F);
        rightearupper = new ModelRenderer(this, 0, 0);
        rightearupper.addBox(0F, 0F, 0F, 1, 3, 1);
        rightearupper.setRotationPoint(-7F, -6F, 0F);
        rightearupper.setTextureSize(64, 32);
        rightearupper.mirror = true;
        setRotation(rightearupper, 0F, 0F, 0F);
        leftearupper = new ModelRenderer(this, 0, 0);
        leftearupper.addBox(0F, 0F, 0F, 1, 3, 1);
        leftearupper.setRotationPoint(6F, -6F, 0F);
        leftearupper.setTextureSize(64, 32);
        leftearupper.mirror = true;
        setRotation(leftearupper, 0F, 0F, 0F);
        cordmid = new ModelRenderer(this, 0, 0);
        cordmid.addBox(0F, 0F, 0F, 1, 9, 1);
        cordmid.setRotationPoint(-1F, -5F, 5F);
        cordmid.setTextureSize(64, 32);
        cordmid.mirror = true;
        setRotation(cordmid, 0F, 0F, 0F);
        cordupper = new ModelRenderer(this, 0, 0);
        cordupper.addBox(0F, 0F, 0F, 1, 1, 2);
        cordupper.setRotationPoint(-1F, -5F, 4F);
        cordupper.setTextureSize(64, 32);
        cordupper.mirror = true;
        setRotation(cordupper, 0F, 0F, 0F);
        cordlower = new ModelRenderer(this, 0, 0);
        cordlower.addBox(0F, 0F, 0F, 1, 1, 4);
        cordlower.setRotationPoint(-1F, 3F, 2F);
        cordlower.setTextureSize(64, 32);
        cordlower.mirror = true;
        setRotation(cordlower, 0F, 0F, 0F);
        head = new ModelRenderer(this, 0, 0);
        head.addBox(-4F, -8F, -4F, 8, 8, 8);
        head.setRotationPoint(0F, 0F, 0F);
        head.setTextureSize(64, 32);
        head.mirror = true;
        setRotation(head, 0F, 0F, 0F);
        body = new ModelRenderer(this, 16, 16);
        body.addBox(-4F, 0F, -2F, 8, 12, 4);
        body.setRotationPoint(0F, 0F, 0F);
        body.setTextureSize(64, 32);
        body.mirror = true;
        setRotation(body, 0F, 0F, 0F);
        rightarm = new ModelRenderer(this, 40, 16);
        rightarm.addBox(-3F, -2F, -2F, 2, 8, 4);
        rightarm.setRotationPoint(-3F, 2F, 0F);
        rightarm.setTextureSize(64, 32);
        rightarm.mirror = true;
        setRotation(rightarm, 0F, 0F, 0F);
        leftarm = new ModelRenderer(this, 40, 16);
        leftarm.addBox(-1F, -2F, -2F, 2, 8, 4);
        leftarm.setRotationPoint(5F, 2F, 0F);
        leftarm.setTextureSize(64, 32);
        leftarm.mirror = true;
        setRotation(leftarm, 0F, 0F, 0F);
        rightleg = new ModelRenderer(this, 0, 16);
        rightleg.addBox(-2F, 0F, -2F, 2, 12, 4);
        rightleg.setRotationPoint(-2F, 12F, 0F);
        rightleg.setTextureSize(64, 32);
        rightleg.mirror = true;
        setRotation(rightleg, 0F, 0F, 0F);
        leftleg = new ModelRenderer(this, 0, 16);
        leftleg.addBox(-2F, 0F, -2F, 2, 12, 4);
        leftleg.setRotationPoint(4F, 12F, 0F);
        leftleg.setTextureSize(64, 32);
        leftleg.mirror = true;
        setRotation(leftleg, 0F, 0F, 0F);
    }

    public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
    {
        super.render(entity, f, f1, f2, f3, f4, f5);
        setRotationAngles(f, f1, f2, f3, f4, f5, entity);
        rightearlower.render(f5);
        leftearlower.render(f5);
        rightearupper.render(f5);
        leftearupper.render(f5);
        cordmid.render(f5);
        cordupper.render(f5);
        cordlower.render(f5);
        head.render(f5);
        body.render(f5);
        rightarm.render(f5);
        leftarm.render(f5);
        rightleg.render(f5);
        leftleg.render(f5);
    }

  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }

  public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5, Entity entity)
  {
    super.setRotationAngles(f, f1, f2, f3, f4, f5, entity);

    float f6 = (180F/(float)Math.PI);

    this.leftleg.rotateAngleX = MathHelper.cos(f * 0.6662F) * 1.4F * f1;
    this.rightleg.rotateAngleX = MathHelper.cos(f  * 0.6662F + (float)Math.PI) * 1.4F * f1;
  }

  public void addRenderer(Map var1)
  {
    var1.put(EntityBotBuddyMob.class, new RenderBiped(new ModelBiped(),.5f));
  }


}